### PR TITLE
Upgraded libs to more recent versions. Added csrf token. Using lein-ring.

### PR DESCRIPTION
**Pull request by ulsa**
Upgraded to Clojure 1.7, java.jdbc 0.4, postgresql 9.3, Compojure 1.4.0. Using ring-defaults to get a nice default set of middleware, which includes CSRF, so a token field is added to the form. Also changed from main to lein-ring, and changed Procfile accordingly.

Everything has been tested on Heroku.

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks, but I think it would be confusing to use lein-ring for this. The benefits of lein-ring really don't apply when running on heroku; it's much simpler to stick with the standard entry point.

The other changes look good, except that this codebase goes along with [a tutorial article in the heroku devcenter](https://devcenter.heroku.com/articles/clojure-web-application), so if the code doesn't match the explanation in that article it won't make sense. Pinging @jkutner to see what he thinks about updating the devcenter article.

**Comment by jkutner** [comment]
I'll be glad to update the tutorial. It may take me a few days, so would be great if we could hold off on merging this until then. I agree that we should stick with the uberjar

**Comment by technomancy** [comment]
@jkutner sounds good. Went ahead and added you as a collab, so merge at your leisure.

**Comment by ulsa** [comment]
Changed back to main and uberjar. Should I remove the lein-ring stuff altogether?

**Comment by jkutner** [comment]
@ulsa yea, I think it would be best to remove lein-ring altogether. It definitely has benefits even when building an uberjar, but for the purpose of the tutorial I'd like to keep it out. But it's up to @technomancy

**Comment by jkutner** [comment]
Updated: https://devcenter.heroku.com/articles/clojure-web-application

**Comment by jkutner** [comment]
@ulsa thanks a ton!

**Pull request merged**
